import { useState } from "react";
import { ArrowDown, ArrowUp, ChevronDown, Pencil, Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { FormField, Input, NativeSelect, Textarea } from "@/components/ui/form-field";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { useMarkdownSelection } from "./MarkdownSelection";
import { moveItem, moveSection } from "@/features/resume/document";
import { ENTRY_TYPES, entryFields, entryType, fieldLabel, isMapping, renameSection, networkOptions } from "@/features/resume/editorModel";
import type { ResumeDocument, ResumeEntry } from "@/features/resume/types";
export type DocumentChange = (document: ResumeDocument, key?: string | null) => void;
const markdownFields = new Set(["bullet", "number", "reversed_number", "text", "label", "details", "summary", "highlights", "authors", "title", "name", "journal", "company", "position", "institution", "area", "degree"]);
export function ValueField({ name, value, change, path = name, markdown = markdownFields.has(name), options = [], seed = "", fixed = false }: {
  name: string; value: unknown; change: (value: unknown, key?: string | null) => void; path?: string; markdown?: boolean; options?: string[]; seed?: unknown; fixed?: boolean;
}) {
  const select = useMarkdownSelection();
  const onSelect = (event: React.SyntheticEvent<HTMLInputElement | HTMLTextAreaElement>) => { const element = event.currentTarget; if (markdown) select({ element, text: element.value, start: element.selectionStart ?? 0, end: element.selectionEnd ?? 0, commit: next => change(next, null) }); };
  const title = fieldLabel(name), attributes = { "aria-label": `${title} · ${path}`, "data-edit-key": path, "data-markdown": markdown || undefined };
  if (Array.isArray(value)) return <div className={`rw-list${fixed ? " rw-fixed-list" : ""}`}><div className="rw-list-heading"><span>{title}</span>{!fixed && <Button variant="link" size="sm" aria-label={`Add ${title} item · ${path}`} onClick={() => change([...value, structuredClone(seed)], null)}><Plus />Add</Button>}</div>{value.map((item, index) => <div className="rw-list-item" key={index}><ValueField name={fixed ? String(index + 1) : name} value={item} path={`${path} item ${index + 1}`} markdown={markdown} change={(next, key) => change(value.map((old, i) => i === index ? next : old), key)} />{!fixed && <div className="rw-item-actions"><Button variant="ghost" size="icon" disabled={index === 0} aria-label={`Move ${title} item ${index + 1} up · ${path}`} onClick={() => change(moveItem(value, index, -1), null)}><ArrowUp /></Button><Button variant="ghost" size="icon" disabled={index === value.length - 1} aria-label={`Move ${title} item ${index + 1} down · ${path}`} onClick={() => change(moveItem(value, index, 1), null)}><ArrowDown /></Button><Button variant="ghost" size="icon" aria-label={`Remove ${title} item ${index + 1} · ${path}`} onClick={() => change(value.filter((_, i) => i !== index), null)}><Trash2 /></Button></div>}</div>)}</div>;
  if (isMapping(value)) return <div className="rw-object">{Object.entries(value).map(([key, item]) => <ValueField key={key} name={key} value={item} path={`${path} ${key}`} change={(next, editKey) => change({ ...value, [key]: key === "url" && next === "" ? null : next }, editKey)} />)}</div>;
  if (typeof value === "boolean") return <div className="rw-field-row"><span>{title}</span><Checkbox aria-label={`${title} · ${path}`} checked={value} onCheckedChange={next => change(next === true, null)} /></div>;
  const long = ["bullet", "number", "reversed_number", "details", "summary", "text", "highlights", "authors"].includes(name);
  return <div className="rw-field-row"><FormField label={title}>{(name === "network" ? networkOptions : options).length ? <NativeSelect {...attributes} value={String(value ?? "")} onChange={event => change(event.target.value, null)}>{!(name === "network" ? networkOptions : options).includes(String(value ?? "")) && <option value={String(value ?? "")}>{String(value ?? "Choose…")}</option>}{(name === "network" ? networkOptions : options).map(option => <option key={option} value={option}>{fieldLabel(option)}</option>)}</NativeSelect> : long ? <Textarea {...attributes} onSelect={onSelect} onKeyUp={onSelect} onMouseUp={onSelect} rows={1} value={String(value ?? "")} onChange={event => change(event.target.value, path)} /> : <Input {...attributes} onSelect={onSelect} onKeyUp={onSelect} onMouseUp={onSelect} type={typeof value === "number" ? "number" : "text"} value={String(value ?? "")} onChange={event => change(typeof value === "number" && event.target.value !== "" ? Number(event.target.value) : event.target.value, path)} />}</FormField></div>;
}
function EntryEditor({ entry, index, title, change }: { entry: ResumeEntry; index: number; title: string; change: (entry: ResumeEntry, key?: string | null) => void }) {
  if (typeof entry === "string") return <ValueField name="text" value={entry} path={`${title} entry ${index + 1}`} change={(next, key) => change(String(next), key)} />;
  return <>{entryFields(entry).map(key => <ValueField key={key} name={key} value={entry[key] ?? (["authors", "highlights"].includes(key) ? [] : "")} path={`${title} entry ${index + 1} ${key}`} change={(value, editKey) => change({ ...entry, [key]: value === "" && !Object.hasOwn(ENTRY_TYPES[entryType(entry)] as Record<string, unknown>, key) ? null : value }, editKey)} />)}</>;
}
function SectionEntries({ entries, title, replace }: { entries: ResumeEntry[]; title: string; replace: (items: ResumeEntry[], key?: string | null) => void }) {
  const [newType, setNewType] = useState("Bullet");
  const type = entries.length ? entryType(entries[0]) : newType;
  return <div className="rw-entries">{entries.map((entry, index) => <div className="rw-entry" key={index} data-entry={index}><div className="rw-entry-heading"><span>{type} {index + 1}</span><div className="rw-item-actions"><Button variant="ghost" size="icon" disabled={!index} aria-label={`Move ${title} entry ${index + 1} up`} onClick={() => replace(moveItem(entries, index, -1), null)}><ArrowUp /></Button><Button variant="ghost" size="icon" disabled={index === entries.length - 1} aria-label={`Move ${title} entry ${index + 1} down`} onClick={() => replace(moveItem(entries, index, 1), null)}><ArrowDown /></Button><Button variant="ghost" size="icon" aria-label={`Remove ${title} entry ${index + 1}`} onClick={() => replace(entries.filter((_, i) => i !== index), null)}><Trash2 /></Button></div></div><EntryEditor entry={entry} index={index} title={title} change={(next, key) => replace(entries.map((old, i) => i === index ? next : old), key)} /></div>)}<div className="rw-entry-add"><NativeSelect aria-label={`Entry type · ${title}`} value={type} disabled={entries.length > 0} onChange={event => setNewType(event.target.value)}>{Object.keys(ENTRY_TYPES).map(name => <option key={name}>{name}</option>)}</NativeSelect><Button variant="link" size="sm" aria-label={`Add entry · ${title}`} onClick={() => replace([...entries, structuredClone(ENTRY_TYPES[type])], null)}><Plus />Add {type.toLowerCase()} entry</Button></div></div>;
}
function PersonalField({ name, value, seed, change }: { name: string; value: unknown; seed: unknown; change: (value: unknown, key?: string | null) => void }) {
  return <><ValueField name={name} path={`Personal ${name}`} markdown={false} value={value} seed={seed} change={change} />{["email", "phone", "website"].includes(name) && !Array.isArray(value) && <Button variant="link" size="sm" className="rw-add-contact" aria-label={`Add another ${name}`} onClick={() => change(value ? [value, ""] : [""], null)}><Plus />Add another {name}</Button>}</>;
}
export function ResumeForm({ document, change, remove, add, collapsed, toggle }: { document: ResumeDocument; change: DocumentChange; remove: (title: string) => void; add: () => void; collapsed: Set<string>; toggle: (title: string) => void }) {
  const [renaming, setRenaming] = useState(""), [name, setName] = useState(""), [error, setError] = useState("");
  const fields = ["name", "headline", "location", "email", "phone", "website", "social_networks", "custom_connections"];
  const setPersonal = (key: string, value: unknown, editKey?: string | null) => change({ ...document, cv: { ...document.cv, [key]: value === "" ? null : value } }, editKey);
  return <div className="rw-cv-form"><section className="rw-section rw-personal" data-title="Personal information"><div className="rw-section-heading"><Button variant="ghost" className="rw-section-toggle" aria-expanded={!collapsed.has("@personal")} onClick={() => toggle("@personal")}><ChevronDown />Personal information</Button></div>{!collapsed.has("@personal") && <div className="rw-section-body">{fields.map(key => <PersonalField key={key} name={key} value={document.cv[key] ?? (["social_networks", "custom_connections"].includes(key) ? [] : "")} seed={key === "social_networks" ? { network: "", username: "" } : key === "custom_connections" ? { fontawesome_icon: "", placeholder: "", url: null } : ""} change={(value, editKey) => setPersonal(key, value, editKey)} />)}{Object.keys(document.cv).some(key => ![...fields, "sections"].includes(key)) && <p className="rw-small">Additional fields are retained in YAML.</p>}</div>}</section>
    {Object.entries(document.cv.sections ?? {}).map(([title, entries], index, all) => <section className="rw-section" key={title} data-title={title}><div className="rw-section-heading"><Button variant="ghost" className="rw-section-toggle" aria-expanded={!collapsed.has(title)} onClick={() => toggle(title)}><ChevronDown />{title}</Button><div className="rw-item-actions"><Button variant="ghost" size="icon" aria-label={`Rename ${title} section`} onClick={() => { setRenaming(title); setName(title); setError(""); }}><Pencil /></Button><Button variant="ghost" size="icon" aria-label={`Move ${title} section up`} disabled={index === 0} onClick={() => change(moveSection(document, title, -1), null)}><ArrowUp /></Button><Button variant="ghost" size="icon" aria-label={`Move ${title} section down`} disabled={index === all.length - 1} onClick={() => change(moveSection(document, title, 1), null)}><ArrowDown /></Button><Button variant="ghost" size="icon" aria-label={`Delete ${title} section`} onClick={() => remove(title)}><Trash2 /></Button></div></div>{!collapsed.has(title) && <div className="rw-section-body"><SectionEntries entries={entries} title={title} replace={(next, key) => change({ ...document, cv: { ...document.cv, sections: { ...document.cv.sections, [title]: next } } }, key)} /></div>}</section>)}
    <Button variant="link" className="rw-add-section" onClick={add}><Plus />Add section</Button>
    <Dialog open={Boolean(renaming)} onOpenChange={open => { if (!open) setRenaming(""); }}><DialogContent><DialogHeader><DialogTitle>Rename chapter</DialogTitle><DialogDescription>Keep a unique title. Entries and chapter order are preserved.</DialogDescription></DialogHeader><FormField label="New chapter title"><Input value={name} maxLength={100} onChange={event => setName(event.target.value)} /></FormField>{error && <p role="alert">{error}</p>}<DialogFooter><Button variant="outline" onClick={() => setRenaming("")}>Cancel</Button><Button onClick={() => { try { change(renameSection(document, renaming, name), null); setRenaming(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Choose another title."); } }}>Rename</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
