import { Link } from 'react-router-dom';
import { Drawer, DrawerContent, DrawerHeader, DrawerTitle, DrawerDescription, DrawerBody } from '@/components/ui/drawer';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { AppButton } from '@/components/ui/app-button';
import type { Course } from '@/pages/LearningCentre/types';
import type { PlanEvent } from './planModel';
export default function PlanCourseDrawer({ course, events, onClose, onEdit }: { course: Course; events: PlanEvent[]; onClose: () => void; onEdit: (event: PlanEvent) => void }) {
  return <Drawer open onOpenChange={open => { if (!open) onClose(); }}><DrawerContent className="sm:max-w-2xl"><DrawerHeader><p className="text-sm uppercase tracking-widest text-[#4f91ba]">{course.provider}</p><DrawerTitle>{course.title} <span className="ml-2 inline-block rounded-full bg-[#f4e1e9] px-3 py-1 text-xs text-[#9c5f78]">In learning plan</span></DrawerTitle><DrawerDescription>{course.level} · {course.language}</DrawerDescription></DrawerHeader><DrawerBody><Tabs defaultValue="overview"><TabsList className="w-full"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="chapters">Chapters</TabsTrigger><TabsTrigger value="schedule">Schedule</TabsTrigger></TabsList><TabsContent value="overview" className="space-y-5 pt-4"><h3 className="font-semibold text-[#3d5f7a]">About this course</h3><p>{course.intro}</p><h3 className="font-semibold text-[#3d5f7a]">What you will learn</h3><ul className="list-disc space-y-2 pl-5">{course.outcomes.map(item => <li key={item}>{item}</li>)}</ul><h3 className="font-semibold text-[#3d5f7a]">Before you start</h3><p>{course.prereq}</p></TabsContent><TabsContent value="chapters" className="space-y-3 pt-4">{course.chapters?.length ? course.chapters.map((chapter, index) => <div key={index} className="rounded-xl bg-white p-4">{index + 1}. {chapter.title}{chapter.min !== null && <span className="ml-2 text-sm text-[#7f7280]">{chapter.min} min</span>}</div>) : <p>The provider has not supplied a chapter list.</p>}</TabsContent><TabsContent value="schedule" className="space-y-3 pt-4">{events.slice().sort((a,b) => a.date.localeCompare(b.date) || a.start.localeCompare(b.start)).map(event => <div key={event.id} className="flex items-center justify-between gap-3 rounded-xl bg-white p-4"><div>{event.date}<p className="text-sm text-[#4f91ba]">{event.start}–{event.end} · {event.completed ? 'Completed' : 'Planned'}</p></div><button className="text-sm text-[#4f91ba]" onClick={() => onEdit(event)}>Edit time</button></div>)}</TabsContent></Tabs></DrawerBody><AppButton tone="gradient" asChild><Link to={`/learning-centre?q=${encodeURIComponent(course.title)}`}>View in Learning Resources →</Link></AppButton></DrawerContent></Drawer>;
}
